### ISSUE TITLE
Webpage url issue

### ISSUE THREAD

**Issue by ReallySteelz** [Anistream/Anistream-Mobile#111]
It gave me some issue page and won't go to server

**Comment by Sdark19** [comment]
The issue is fixed you should close this issue

**Comment by Lavish883** [comment]
Bro i fixed it this zip file contains the apk before installing it delete anistream be sure to have a backup of ur saved anime data of anistream before deleting.
[anistream.zip](https://github.com/Anistream/Anistream-Mobile/files/5188302/anistream.zip)

**Comment by ReallySteelz** [comment]
Thnx
