### ISSUE TITLE
Amoled Theme

### ISSUE THREAD

**Issue by GoluLiliput** [Anistream/Anistream-Mobile#12]
Hey @Riku32 , Just one thing I want... Please update the app just once by creating an amoled theme for the app... Please make the background of the app completely black.
This is my final request to u brother..

Or just tell me how canni do so by decompiling the elements of the app apk file... Do I need to edit any manifest or something?

**Comment by Riku32** [comment]
There are some xml files and values where you can change stuff around, you should be able to see somewhere with the colors, make sure you use android studio to compile. All the things to change should be in the res directory. I'm not making it public because I'm not making a color switcher, but if you want a custom version that's all you need to do.

**Comment by GoluLiliput** [comment]
Can I get some more help... I located the res folder and all the assets inside it. I will compile the whole apk later keeping signatures intact. Pls tell me what values I change and where.
Thanks for ur quick reply tho brother

**Comment by Riku32** [comment]
It is in XML files, I think some are in values.xml and some are in other XML's. They look like color hex codes in the format of "#FFFFFF". That's all I can tell you, they will probably highlight in Android Studio

**Comment by GoluLiliput** [comment]
Ok bro I will go around those files...
What about the server problem resurfacing bro?

**Comment by Riku32** [comment]
The server problem has died out recently, it still shows up but it's gone away and comes back in waves. I don't expect it to last very long, it's just a temporary issue with vidstream.

**Comment by GoluLiliput** [comment]
So due to vidstream only the whole app is facing this trouble? 
Hm now I get it...

**Comment by GoluLiliput** [comment]
I got the color.xml inside the values subdirectory inside the res directory... There are many color elements... Which element shout I tweak and replace?

**Comment by Riku32** [comment]
you should be able to look at the color codes and the app and figure it out, some colors are spread out in other files aswell.

**Comment by GoluLiliput** [comment]
Thanks bro

**Comment by GoluLiliput** [comment]
I just need to change the codes everywhere tht goes by the #xxxxxxx

**Comment by Riku32** [comment]
No there are many codes, #FFFFFF is an example for white

**Comment by GoluLiliput** [comment]
I will do it... But brother why don't u push the amoled theme of the app along with the update u mentioned u will push tomorrow? 
Definitely me n my friends would much appreciate that

**Comment by Riku32** [comment]
Because I won't be making a color selector, it would make the entire app AMOLED. There might be something in the future like a rewrite which I'm thinking about which would have this feature if we do rewrite it the app will go back to closed source but the current code will stay public.

**Comment by GoluLiliput** [comment]
Ok bro I understand
