### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by Riku32** [Anistream/Anistream-Mobile#13]
It has come to my attention that vidstream will be changing the format of video that we use for our  main source, a small update will be pushed tomorrow to use fallback sources and update some information on the app itself. If you have a recent version of the app it will automatically detect an update on launch. Once again sorry for any issues and tomorrow hopefully the app will function as intended.

**Comment by Wolfkid200444** [comment]
ok

**Comment by GoluLiliput** [comment]
Thanks a lots bro. I rilly love this app

**Comment by Riku32** [comment]
Server issues should be fixed with the new scraper update :3

**Comment by CR4KE** [comment]
Thank you so much!
