### ISSUE TITLE
New episodes in unkown res over a week after release

### ISSUE THREAD

**Issue by Giosel** [Anistream/Anistream-Mobile#14]
As the title says, new episodes, mostly from long running shonens (e.g. One Piece, Boruto) stay in the unkown res well over a week after their initial release and struggle to load. I heard it was because of encoding, but it never used to take this long.

**Comment by CR4KE** [comment]
I've noticed new releases get stuck and won't load after it's loaded a certain ammount

**Comment by Giosel** [comment]
Is that right after they've been released, or is it after a while?

**Comment by CR4KE** [comment]
Newer stuff (I've only checked newer episodes front he past few days), older series I find work perfectly well

**Comment by Giosel** [comment]
Just to double check, can you check boruto ep 152 and One Piece ep 928? (Both from 7 days ago)

**Comment by CR4KE** [comment]
I checked they both load fine but neither have a option of changing quality

**Comment by iAlexPlays** [comment]
I tried Boruto ep153 (came out today) but in my case, it doesn't even want to start the vid, and i'm trying to watch naruto shippuden, but same problem each time, so can't watch anything anymore! How can i fix this?!?

**Comment by Giosel** [comment]
That's a different issue i think. If you check vidstreaming directly it says the episodes in questions are played from the Cloud9 server. Yeah, it's annoying, thankful it's only some episodes and they get fixed after a while :(

**Comment by iAlexPlays** [comment]
Giozel, wdym?

**Comment by iAlexPlays** [comment]
I doesn't want to start the vid, i'm not even getting redirected. It just doesn't start!

**Comment by iAlexPlays** [comment]
And the quality remains "unknown"

**Comment by Giosel** [comment]
https://vidstreaming.io/videos/boruto-naruto-next-generations-episode-153

**Comment by iAlexPlays** [comment]
Oh....thx!!!!

**Comment by CR4KE** [comment]
For some reason on my tablet, newer series and episode won't load or stop loading straight away, but they work fine on my phone? And older series work fine too, is this an issue with the app?

**Comment by Riku32** [comment]
Its because the second server which we used died had quality options more commonly. The quality options only exist for newer episodes after a while.
