### ISSUE TITLE
Is this app still supported by someone or is it left for dead?

### ISSUE THREAD

**Issue by Krisi7575** [Anistream/Anistream-Mobile#153]
If this app is left than can we get some type of announcement because this getting a little frustrating to watch.

**Comment by UserBtw** [comment]
You should give up, I don't think it's coming back.... Use animefanz tube man, it's better and it works my guy. 👌
[Animefanz tube](https://www.google.com/search?q=animefanz+tube&oq=&aqs=chrome.0.69i59i450l3.-1j0j7&client=ms-android-att-us-revc&sourceid=chrome-mobile&ie=UTF-8#)
