### ISSUE TITLE
Don't opening, issues in main server, anime are not showing in there slot

### ISSUE THREAD

**Issue by arpit997** [Anistream/Anistream-Mobile#17]
So there are many things that now i am facing in anistream app like main server is not opening always showing to use different server i don't like use different server because of there interface. There some more issues like may time it automatically stop working then i have to reopen it again and again. Sometimes anime are no in there slots means some time it show that anime not aired, some time nothing only blank screen. There are is an request that pls make the main server interface like netflix -10 sec and -10sec pls pls pls

**Comment by Riku32** [comment]
Update the app with the new APK

**Comment by arpit997** [comment]
Thanks for hearing my req and react in it and now the app is also working
properly so thanks for every thing

**Comment by arpit997** [comment]
Thanks for hearing my req and take action I like your work. The app again started working properly again thanks to solve the problem because of that I can again enjoy watching anime.
