### ISSUE TITLE
Can't search anime anymore 

### ISSUE THREAD

**Issue by waithuh** [Anistream/Anistream-Mobile#21]
![Screenshot_20200421-134332](https://user-images.githubusercontent.com/64098495/79899092-93101480-840c-11ea-8a69-33bc7458126b.jpg)

**Comment by waithuh** [comment]
Sam bro

**Comment by sasaton123** [comment]
I find it on my phone, do u have the latest update? Cuz i saw u words was a bit off than the one i used, u need to reinstall the app again in order to get the latest update, write down all the animes u like cuz some of them will not be saved of some reason

**Comment by waithuh** [comment]
Ok

**Comment by waithuh** [comment]
Still doesn't work
