### ISSUE TITLE
Can't watch

### ISSUE THREAD

**Issue by jotarothe** [Anistream/Anistream-Mobile#22]
The anime doesn't play, only shows black background.

**Comment by DarkGator31** [comment]
Yea same

**Comment by ShisuiUchiha2** [comment]
Same goes for me

**Comment by mhafan15** [comment]
![Screenshot_20200424-000444](https://user-images.githubusercontent.com/64242358/80173911-3e60cb00-85bf-11ea-872e-02e87a306aeb.png)
This is what happens whenever I open the app.

**Comment by Kuramabami** [comment]
Is there any solution to that? @Riku32 😕

**Comment by Riku32** [comment]
Blame vidstreaming, its their servers, just wait.

**Comment by mhafan15** [comment]
Whenever I try to watch a episode, it just shows a black screen and when I check the quality, it says unknown.
