### ISSUE TITLE
A ray of hope to everyone :)

### ISSUE THREAD

**Issue by GoluLiliput** [Anistream/Anistream-Mobile#23]
Guys, this app is shutting down. I haven't asked the developper or anyone of sorts. But he hasn't replied anyone messages and neither does he reply to anyone on discord.
At this point of time, I request everyone to pls lose hope on this app. I sincerely ask everyone to switch to other apps currently. I have mention below few of the amazing alternatives below..... They are much amazing in comparison and have amazing developmental lineup. One of these app even has an amazing community which is supported by donors and beta testers on discord. Tht app even has integrated anime tracker and u can view all ur animes there without the hassle of complaining so much.
I am ranking them according to preference. Please go through it and comment me below about how u like it. N those developpers, unlike this app's developper, do listen to people and do go bragging.

1. Anime Glare (ad-free and and a very powerful anime streaming app with integrated tracker and a huge and active discord community; not available on play store. Visit www.animeglare.xyz both for iOS and Android) 

2. Anime bay

3. AnimeStack 2020

4. Otaku Hub

5. Anime Action

6. Animaze

7. Anime Cast ( download from http://animecast.csc-lab.xyz/ )

8. Animaze

I will update u for more later. Till then definitely try these app out. All of them are hell lot better than this shitty Anistream app ever was. Except all have few ads which are not at all intrusive. Most of them could be found on play store itself. 
Enjoy watching anime without intrusion and stay safe from corona everyone. Dont forget to wash hands regularly n stay indoors🙂🙂🙂

**Comment by Giosel** [comment]
Sorry to say, but you invalidated your point in the first two lines. 
Second thing, this app is still leagues above any other app you listed in terms of interface.
Third thing, this feels very shitty and not something that should be posted here.

**Comment by GoluLiliput** [comment]
Lol shut up bro... I have helped ppl here who are complaining here when the developper isn't even listening pretendingly... He is always active on discord and can't even reply. 
And yeah... All the apps I mentioned are league's bttr than than this shitty app in interface as well as functionality. I request people to judge it for themselves n don't listen to this idiot here

**Comment by GoluLiliput** [comment]
That's why I requested people to try and lemme know. M not deaf as the developper of this app himself

**Comment by Giosel** [comment]
I'll wait for anyone to say the other apps you listed are as accessible as this one

**Comment by GoluLiliput** [comment]
Lol let's see. Don't dare support the bitchy developper of this app who is this irresponsible.

**Comment by GoluLiliput** [comment]
M also tired complaining that's why I felt the need to help people out of this fucked up situation.

**Comment by GoluLiliput** [comment]
> Sorry to say, but you invalidated your point in the first two lines. 
> Second thing, this app is still leagues above any other app you listed in terms of interface.
> Third thing, this feels very shitty and not something that should be posted here.

And yeah.... P.S. I didn't invalidate anything. The bitch @Riku32 himself said he was quitting development of this app in past.

**Comment by GoluLiliput** [comment]
Guys please check out the app definitely n lemme know if it helped.

**Comment by Riku32** [comment]
Yeah i dont want you in my comments every minute you can, im not working on anistream every moment of my life, i have a life too unlike some people lmao

**Comment by Riku32** [comment]
Oh yeah btw, this started as a personal project, I'm the only dev working on it. Dont expect me to be responsible, it was made for me, not you. I made it public for you to enjoy while it lasted.

**Comment by CR4KE** [comment]
I completely understand riku, does this mean you'll be stop working on the app? It was a great app well it lasted, thank you for your time 😀

**Comment by Riku32** [comment]
It still works for me actually, no idea what people are complaining about. If it breaks for me ill update it

**Comment by Giosel** [comment]
I'll at least say what isn't working for me so can you guys confirm if it's a problem on your end as well?
1. Unkown res stays for a while (more than a week in some cases)
2. Some episodes don't play at all(could confirm it in early one piece episodes and boruto ones). 
That's all

**Comment by CR4KE** [comment]
It seems to work fine for me too, the only issue I have is some newer episodes not playing on my tablet for some reason, they stop working a few seconds in, but work fine on my phone.
