### ISSUE TITLE
One episode crashed the app

### ISSUE THREAD

**Issue by InkLuigi** [Anistream/Anistream-Mobile#3]
One episode that the app close and/or stop working. And that is Love live dub episode 9. When I opened it crash. Please fix this ASAP!

**Comment by GoluLiliput** [comment]
No sir it's working fine

**Comment by GoluLiliput** [comment]
Please lemme know about your email. I will send u a modified apk

**Comment by Riku32** [comment]
Can you please provide me with screenshots or screencap of this happening?
I need to know specifics like what the episode number was, the anime, and other stuff.
Issues like these are usually weird naming schemes or the sources have an episode number despite not having any content attached.

**Comment by Riku32** [comment]
Sorry, didn't see that you provided details, after looking further it seems that episode works perfectly so I'm closing this issue now

**Comment by InkLuigi** [comment]
It's: Love live - school idol project ENGLISH DUB episode 9

**Comment by GoluLiliput** [comment]
> One episode that the app close and/or stop working. And that is Love live dub episode 9. When I opened it crash. Please fix this ASAP!

No the app doesn't crash. I rechecked. It ur device specific bug bro

**Comment by InkLuigi** [comment]
I see, but will it fix it soon?

**Comment by InkLuigi** [comment]
Thanks for nothing >:( I'll be deleted from the app and never use it again
