### ISSUE TITLE
App keeps stopping

### ISSUE THREAD

**Issue by derpypoodles** [Anistream/Anistream-Mobile#42]
Hi! I really love your app and have been using it since before your site got taken down. A few days ago it just decided to stop working. It keeps saying that the app keeps stopping and I can't do anything about it. I'm on a Samsung a70 in case it is a compatibility issue.

**Comment by Giosel** [comment]
Same here, 
Was working 2 hours ago tho

**Comment by derpypoodles** [comment]
It is fixed now. I don't know what happened but Im glad it was just a temporary issue

**Comment by Murphy05** [comment]
Works perfectly for me love the app never failed to find a anime that I was
looking for and the very few bugs that I come across are very minor. Great
app keep up the good work and I hope you can get the app back up Ann running
