### ISSUE TITLE
Heres how to fix the loading issue so you can actually watch anime lol.

### ISSUE THREAD

**Issue by uummlols** [Anistream/Anistream-Mobile#57]
I know many people are currently wanting a fix because of the issue, it is a big problem so its justified. However as it turns out Riku is considering dropping development and maybe has already done so, so please give him a bit of break even though I get why you guys are mad. Anyways, the way to fix the massive issue for me was to downgrade to the 1.3.17 (1 release below the current version ) tell me if this works for you guys. ( PS: Riku please dont drop this amazing app you have made a really great service that not only gives mobile users anime but it is all free without any ads, nobody really appreciates just how insane that is, a free service in a market where nobody cares about anything but profit, simply amazing)

**Comment by CR4KE** [comment]
I gave that a try and the 1.3.17 works ok for the anime I tried, but the streams are riddled with ads, because I'm guessing it doesn't have the scrapers updated

**Comment by uummlols** [comment]
Oh yea I forgot there are ads, but they arent intrusive like some of the ads in services such as Crunchyroll, atleast you can still watch anime.

**Comment by CR4KE** [comment]
I only tried one anime but from what I can remember I think they was quite intrusive, constantly popping up and such, but I'll just wait until riku fixes it, if they do

**Comment by Kippaktsoep** [comment]
how or where do you change/download the 1.3.17 release?

**Comment by CR4KE** [comment]
Go to code section, scroll down to releases, click the "+ 1 release", under the 1.3.17 section will be a section "3 assets" click that and then download the app file

**Comment by uummlols** [comment]
Hopefully he does fix it, the ads were never a major problem for me though, they rarely ever pop up.

**Comment by CR4KE** [comment]
Yeah fingers crossed riku fixes it or someone else takes over the app, it's one of the best free anime apps I've came across, would be sad to lose it

**Comment by king7kross** [comment]
Yeah i hope too that he fixes it
I heard they took over this app from other source months ago but i wonder why this app gets bugged🙃

**Comment by uummlols** [comment]
Its probably the only free anime app I know of that has a decent quality and such a large amount of anime, would be a huge shame to see it go under.

**Comment by kiyoshinsei** [comment]
actually pog dude. This is remarkable

**Comment by Vatsl3008** [comment]
Thnx man for ur suggestion . Riku plzz try to fix the bug . We all need you ...

**Comment by Rezert-g** [comment]
> Yeah i hope too that he fixes it
> I heard they took over this app from other source months ago but i wonder why this app gets bugged

Yea it was owned by someone who wanted people to watch anime for free without ads so the person who created it to a few months to get all the coding right and it was like that for a while until riku decided to buy it from the creator

**Comment by Rezert-g** [comment]
> Go to code section, scroll down to releases, click the "+ 1 release", under the 1.3.17 section will be a section "3 assets" click that and then download the app file

When i went to download it, it said that it was corrupt

**Comment by meme-alchemist** [comment]
> > Go to code section, scroll down to releases, click the "+ 1 release", under the 1.3.17 section will be a section "3 assets" click that and then download the app file
> 
> When i went to download it, it said that it was corrupt

all you need to do is delete the current anistream app first and then download the older version.
i had the same problem yesterday and i delete it first and it got installed.
tell me if this works for you

**Comment by balvinderz** [comment]
you guys can use my app 
https://github.com/balvinderz/animewatcher/tree/master/app/release

**Comment by Rezert-g** [comment]
It worked thanks man/woman not trying to assume genders here but it works great

**Comment by Silver-Wulf** [comment]
The underlying websites changed structure a little so the app just needed a tiny change. I think I have it fixed in #67 but I cannot deploy a release APK since I do not have a copy of the keys.

**Comment by Riku32** [comment]
This right here, the app has been completely fixed and I might be adding Chromecast and a few other things soon. So yeah I just needed a break from Anistream and piracy stuff. Was trying to expand programming knowledge and still am(currently learning Rust).
