### ISSUE TITLE
App is blank 

### ISSUE THREAD

**Issue by VinodKrBhardwaj** [Anistream/Anistream-Mobile#66]
Hello i think app is not working properly because it is showing blank screen in the starting if anyone is getting the same problem please tell

**Comment by animeforever200323** [comment]
I think development has been stopped

**Comment by VinodKrBhardwaj** [comment]
@animeforever200323  yours is also not working?

**Comment by Kokunut965** [comment]
Sto reopening this issue. If we spam issues he will completely drop the app

**Comment by VinodKrBhardwaj** [comment]
Ok
