### ISSUE TITLE
crashes when i open a new anime

### ISSUE THREAD

**Issue by stefgrams44** [Anistream/Anistream-Mobile#70]
I have a problem that when i type a anime in the searchbar it crashes and i have to reopen the app to no make it crash each time i want to search a new anime

Btw thanks for fixing the app

**Comment by VinodKrBhardwaj** [comment]
Bro i think you are using old version there is a new update which come yesterday all the issues are fixed or maybe there must be an internet problem

**Comment by stefgrams44** [comment]
Thanks i reinstalled the app and it worked
