### ISSUE TITLE
App is totally blank

### ISSUE THREAD

**Issue by sanjay19bar** [Anistream/Anistream-Mobile#87]
First only the episodes are are stuck inn 00:00 now the total app is blank now even older version is not working

**Comment by animeforever200323** [comment]
Lots of anime sites are getting shut down

**Comment by ShadoWarrior04** [comment]
Ya... Even kissanime is not working

**Comment by TFlame125** [comment]
Its sad because I love anime but can't afford to pay for premium anime and since anistream is down I'm at a roadblock

**Comment by krtsom** [comment]
did you try gogoanime
