### ISSUE TITLE
The app is totally blank

### ISSUE THREAD

**Issue by Chuo6** [Anistream/Anistream-Mobile#89]
For some reason the application isn't working at all I can't enter any anime and when I do that it says not aired even though the anime that I looked up for were done and even when I pressed on a random anime it still says the same I tried older versions but none worked I hope that you fix this soon I'll be patiently waiting for the next update and I'm really thankful for the anime application it's the only good app for anime I found thank you so much I hope you fix this as soon as possible ❤️

**Comment by MilkyWayys** [comment]
Maybe because of the new law in Jap that just copyright every pirating anime sites/apps.

**Comment by Chuo6** [comment]
Really but I have another anime app and it seems to be working just fine

**Comment by VinodKrBhardwaj** [comment]
Actually the new law will be applied on january 2021 so that would not be a problem for now and I'm also using another app and it is working fine with me
