### ISSUE TITLE
More app issues... smh

### ISSUE THREAD

**Issue by YTTheNewKiller26** [Anistream/Anistream-Mobile#92]
Riku the app crashes right after a sub episode ends or if you try to skip a episode. And the dubs are in a browser like state please fix it. <3
![Screenshot_20200818-224607](https://user-images.githubusercontent.com/53920434/90563816-a22d8600-e1a4-11ea-83b8-591b57eb7570.jpg)

**Comment by animeforever200323** [comment]
At least its working

**Comment by Silver-Wulf** [comment]
As far as I know, only a small set of the anime should appear like that. I am not 100% on why that happens but I can take a look later.

**Comment by VinodKrBhardwaj** [comment]
It can be fixed or not sir can you tell please 🙏

**Comment by VinodKrBhardwaj** [comment]
@Silver-Wulf  please tell

**Comment by Silver-Wulf** [comment]
I just created a PR that should fix a lot of these, waiting on approval

**Comment by VinodKrBhardwaj** [comment]
@Silver-Wulf  sir the app is suddenly opening in a Browser as I was watching naruto shippuden and it crashes and dub are opening in the browser state

**Comment by Riku32** [comment]
Yeah this has been fixed in the newest version
